[theme]
primaryColor = "#6A994E"            # Cor principal
backgroundColor = "#F4F4F9"         # Cor de fundo
secondaryBackgroundColor = "#A7C957" # Fundo secundário
textColor = "#386641"               # Cor do texto
font = "sans serif"                 # Fonte (opcional)
